GET http://localhost:3000

### Página de login do cliente
POST http://localhost:3000/auth/login

### Página de registro do cliente 
POST http://localhost:3000/auth/register

### Página de carregamento do cliente 
POST http://localhost:3000/auth/refresh-token

### Página de saida do cliente 
DELETE http://localhost:3000/auth/logout