GET http://localhost:5173

### Página de login do cliente
POST http://localhost:5173/auth/login

### Página de registro do cliente 
POST http://localhost:5173/auth/register

### Página de carregamento do cliente 
POST http://localhost:5173/auth/refresh-token

### Página de saida do cliente 
DELETE http://localhost:5173/auth/logout